// Jenkinsfile (Declarative Pipeline)
pipeline {
    agent any
    options {
        skipDefaultCheckout(true)
    }
    environment {
        git_hash = null
        GIT_URL = "${env.GIT_URL}"
        S3_BUCKET_URL = "${env.S3_BUCKET_URL}"
        RDS_ENDPOINT = "${env.RDS_ENDPOINT}"
        AWS_ACCESS_KEY_ID = "${env.AWS_ACCESS_KEY_ID}"
        AWS_SECRET_ACCESS_KEY = "${env.AWS_SECRET_ACCESS_KEY}"
        DB_CREDENTIALS = credentials('db_credentials')
        DOCKERHUB_CREDENTIALS = credentials('dockerhub_credentials')
        BACKEND_ENDPOINT = "${env.BACKEND_ENDPOINT}"
        REDIS_PSW = "${env.REDIS_PSW}"
    }
    stages {
        stage('Checkout helm-charts') { 
            steps {
                script {
                    git_info = checkout([
                        $class: 'GitSCM', branches: [[name: "*/${env.GIT_BRANCH}"]], 
                        doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [], 
                        userRemoteConfigs: [[
                            credentialsId: 'GitToken', 
                            url: "${GIT_URL}"
                            'https://github.com/cyrilsebastian1811/helm-charts.git'
                        ]]
                    ])

                    git_hash = "${git_info.GIT_COMMIT[0..6]}"
                }

                echo "${git_hash}"
            }
        }
        stage('Build Backend Helm Chart installation') { 
            when {
                expression { return sh(returnStdout: true, script: "helm list --filter 'backend+' -q && ") === }
            }
            steps {
                script {
                    sh "pwd"
                    sh "ls -a"
                    // try{
                    //     sh("helm status backend")
                    //     sh "helm upgrade backend ./webapp-backend -n api --set dbUser=${DB_CREDENTIALS_USR},dbPassword=${DB_CREDENTIALS_PSW},imageCredentials.username=${DOCKERHUB_CREDENTIALS_USR},imageCredentials.password=${DOCKERHUB_CREDENTIALS_PSW},rdsEndpoint=${RDS_ENDPOINT},s3Bucket=${S3_BUCKET_URL},awsAccess=${AWS_ACCESS_KEY_ID},awsSecret=${AWS_SECRET_ACCESS_KEY},imageCredentials.registry=https://index.docker.io/v1/"
                    // }catch (exc) {
                    //     sh "helm install backend ./webapp-backend -n api --set dbUser=${DB_CREDENTIALS_USR},dbPassword=${DB_CREDENTIALS_PSW},imageCredentials.username=${DOCKERHUB_CREDENTIALS_USR},imageCredentials.password=${DOCKERHUB_CREDENTIALS_PSW},rdsEndpoint=${RDS_ENDPOINT},s3Bucket=${S3_BUCKET_URL},awsAccess=${AWS_ACCESS_KEY_ID},awsSecret=${AWS_SECRET_ACCESS_KEY},imageCredentials.registry=https://index.docker.io/v1/"
                    // }
                    sh "helm upgrade backend ./webapp-backend -n api --install --set dbUser=${DB_CREDENTIALS_USR},dbPassword=${DB_CREDENTIALS_PSW},imageCredentials.username=${DOCKERHUB_CREDENTIALS_USR},imageCredentials.password=${DOCKERHUB_CREDENTIALS_PSW},rdsEndpoint=${RDS_ENDPOINT},s3Bucket=${S3_BUCKET_URL},awsAccess=${AWS_ACCESS_KEY_ID},awsSecret=${AWS_SECRET_ACCESS_KEY},redis.global.redis.password=${REDIS_PSW},imageCredentials.registry=https://index.docker.io/v1/"
                }
            }
        }
    }
}